/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.19.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as crons from "../crons";
import type * as getContests from "../getContests";
import type * as scrapers_addContests from "../scrapers/addContests";
import type * as scrapers_addProblems from "../scrapers/addProblems";
import type * as scrapers_atcoder_client from "../scrapers/atcoder/client";
import type * as scrapers_atcoder_consts from "../scrapers/atcoder/consts";
import type * as scrapers_atcoder_crawlContests from "../scrapers/atcoder/crawlContests";
import type * as scrapers_atcoder_crawlProblems from "../scrapers/atcoder/crawlProblems";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  crons: typeof crons;
  getContests: typeof getContests;
  "scrapers/addContests": typeof scrapers_addContests;
  "scrapers/addProblems": typeof scrapers_addProblems;
  "scrapers/atcoder/client": typeof scrapers_atcoder_client;
  "scrapers/atcoder/consts": typeof scrapers_atcoder_consts;
  "scrapers/atcoder/crawlContests": typeof scrapers_atcoder_crawlContests;
  "scrapers/atcoder/crawlProblems": typeof scrapers_atcoder_crawlProblems;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
